version: '3.8'

services:
  labelarr:
    image: nullableeth/labelarr:latest
    container_name: labelarr
    restart: unless-stopped
    environment:
      - PLEX_SERVER=localhost
      - PLEX_PORT=32400
      - PLEX_REQUIRES_HTTPS=true
      - PLEX_TOKEN=your_plex_token_here
      - TMDB_API_KEY=your_tmdb_api_key_here
      - PROCESS_TIMER=5m
      - PROCESS_ALL_MOVIE_LIBRARIES=true
      